quarkus:
  application:
    name: rest-heroes
  banner:
    path: banner.txt
  log:
    console:
      format: "%d{HH:mm:ss} %-5p (%t) %s%e%n"
      level: INFO
  hibernate-orm:
    database:
      generation: validate
  datasource:
    reactive:
      url: postgresql://hero:hero@localhost:5432/heroes_database
  http:
    port: 8083
"%dev,test":
  quarkus:
    hibernate-orm:
      hibernate-sql-load-script: import.sql

  rest-client:
    heroes:
      url: http://localhost:3000


  jackson:
    serialization-inclusion: non-empty

  smallrye-openapi:
    info-title: Hero API
    info-description: This API allows CRUD operations on a hero
    info-version: 1.0
    info-contact-name: Quarkus
    info-contact-url: https://github.com/quarkusio
  swagger-ui:
    always-include: true


