quarkus:
  application:
    name: rest-heroes
  banner:
    path: banner.txt
  log:
    console:
      format: "%d{HH:mm:ss} %-5p (%t) %s%e%n"
      level: INFO
  http:
    port: 8083
    cors:
      ~: true
      origins: "*"
  rest-client:
    heroes:
      url: http://localhost:3000
  jackson:
    serialization-inclusion: non-empty
  smallrye-openapi:
    info-title: Hero API
    info-description: This API allows CRUD operations on a hero
    info-version: 1.0
    info-contact-name: Quarkus
    info-contact-url: https://github.com/quarkusio
  swagger-ui:
    always-include: true

"%dev,test":
  quarkus:
    datasource:
      devservices:
        init-script-path: data/initialize-table.sql
    hibernate-orm:
      #hibernate-sql-load-script: data\initialize-table.sql
      database:
        generation: validate
    log:
      console:
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        level: DEBUG

"%prod":
  quarkus:
    datasource:
      reactive:
        url: postgresql://hero:hero@localhost:5432/heroes_database
    hibernate-orm:
      database:
        generation: validate


